// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xualguiyqxutdgybbhie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1YWxndWl5cXh1dGRneWJiaGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MzE5MzcsImV4cCI6MjA4ODMwNzkzN30.KTKMgtbq8YVm-rVlTm22SaWvxVdnpnPCxmoW9v3vhKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});